import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable'; // This import side-effects jsPDF
import { TravelEntry, AddressEntry } from '@/db/db';

// Helper to format dates
const formatDate = (dateStr: string | null) => {
  if (!dateStr) return '';
  return dateStr; // Input is already ISO YYYY-MM-DD, usually fine. 
                  // Could be formatted to DD/MM/YYYY if requested, but ISO is safe.
};

// Helper to calculate days
const getDays = (start: string, end: string | null) => {
  if (!start || !end) return '-';
  const diff = new Date(end).getTime() - new Date(start).getTime();
  const days = Math.ceil(diff / (1000 * 3600 * 24));
  return days > 0 ? days.toString() : '0';
};

const formatDestination = (entry: TravelEntry) => {
  const combined = entry.destination?.trim();
  if (combined) return combined;

  const parts = [
    entry.destinationCity?.trim(),
    entry.destinationCountry?.trim(),
  ].filter((part): part is string => Boolean(part));

  return parts.join(", ");
};

export const exportTravelPDF = (data: TravelEntry[]) => {
  const doc = new jsPDF();

  const tableData = data.map(entry => [
    formatDate(entry.startDate),
    formatDate(entry.endDate),
    getDays(entry.startDate, entry.endDate),
    formatDestination(entry),
    entry.purposeCode
  ]);

  doc.setFontSize(16);
  doc.text('Travel History', 14, 20);
  
  doc.setFontSize(10);
  doc.text('Supplementary Information: Your Travels (IMM 5562)', 14, 28);

  autoTable(doc, {
    startY: 35,
    head: [['From', 'To', 'Days', 'Destination (City, Country)', 'Purpose']],
    body: tableData,
    headStyles: { fillColor: [66, 66, 66] },
    alternateRowStyles: { fillColor: [245, 245, 245] },
    margin: { top: 35 },
    didDrawPage: (data) => {
      // Footer
      const pageSize = doc.internal.pageSize;
      const pageHeight = pageSize.height ? pageSize.height : pageSize.getHeight();
      doc.setFontSize(8);
      doc.text(
        'Generated by Table Builder - Not an official IRCC document', 
        data.settings.margin.left, 
        pageHeight - 10
      );
    }
  });

  doc.save('travel_history.pdf');
};

export const exportAddressPDF = (data: AddressEntry[]) => {
  const doc = new jsPDF();

  const tableData = data.map(entry => [
    formatDate(entry.startDate),
    formatDate(entry.endDate),
    entry.country,
    entry.city || '',
    entry.line1 || ''
  ]);

  doc.setFontSize(16);
  doc.text('Address History', 14, 20);

  autoTable(doc, {
    startY: 35,
    head: [['From', 'To', 'Country', 'City', 'Street Address']],
    body: tableData,
    headStyles: { fillColor: [66, 66, 66] },
    alternateRowStyles: { fillColor: [245, 245, 245] },
    margin: { top: 35 },
    didDrawPage: (data) => {
      // Footer
      const pageSize = doc.internal.pageSize;
      const pageHeight = pageSize.height ? pageSize.height : pageSize.getHeight();
      doc.setFontSize(8);
      doc.text(
        'Generated by Table Builder - Not an official IRCC document', 
        data.settings.margin.left, 
        pageHeight - 10
      );
    }
  });

  doc.save('address_history.pdf');
};
